# Generated by Django 5.1 on 2024-08-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="product",
            field=models.CharField(max_length=255),
        ),
    ]
